#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

fail() {
  echo "test failed: $1" >&2
  exit 1
}

assert_contains() {
  local content="$1"
  local pattern="$2"
  if ! grep -Fq -e "${pattern}" <<<"${content}"; then
    fail "missing pattern '${pattern}' in: ${content:0:300}..."
  fi
}

run_and_check_stability() {
  local script="$1"
  local output="$2"
  local label="$3"
  local expected="_Generated by \`${script}\` on 2000-01-01T00:00:00.000Z._"

  AI_WEBGPU_LAB_GENERATED_AT="2000-01-01T00:00:00.000Z" \
    node "${REPO_ROOT}/${script}" --output "${output}" >/dev/null
  assert_contains "$(cat "${output}")" "${expected}"

  cp "${output}" "${output}.first"
  node "${REPO_ROOT}/${script}" --output "${output}" >/dev/null
  if ! cmp -s "${output}.first" "${output}"; then
    fail "${label} should preserve generated timestamp when content is unchanged"
  fi
}

run_and_check_stability "scripts/render-integration-status.mjs" "${TMP_DIR}/integration.md" "integration status"
run_and_check_stability "scripts/render-sketch-metrics.mjs" "${TMP_DIR}/sketch.md" "sketch metrics"
run_and_check_stability "scripts/render-capabilities-matrix.mjs" "${TMP_DIR}/capabilities.md" "capabilities matrix"

SOURCE_DATE_EPOCH=946684800 \
  node "${REPO_ROOT}/scripts/render-capabilities-matrix.mjs" --output "${TMP_DIR}/epoch.md" >/dev/null
assert_contains "$(cat "${TMP_DIR}/epoch.md")" "_Generated by \`scripts/render-capabilities-matrix.mjs\` on 2000-01-01T00:00:00.000Z._"

echo "generated-dashboard-timestamps test passed"
